<?php
$content = '
    <a class="headline" href="' . $story['url'] . '">' . $story['headline'] . '</a><br />
    <span class="details">' . $story['created_by'] . ' | ' . $comment_count . ' Comments | 
    ' . date('n/j/Y g:i a', strtotime($story['created_on'])) . '</span>';

if(isset($_SESSION['AUTHENTICATED'])) {
    $content .= '
    <form method="post" action="/comment/create">
    <input type="hidden" name="story_id" value="' . $_GET['id'] . '" />
    <textarea cols="60" rows="6" name="comment"></textarea><br />
    <input type="submit" name="submit" value="Submit Comment" />
    </form>';
}

foreach($comments as $comment) {
    $content .= '
    <div class="comment"><span class="comment_details">' . $comment['created_by'] . ' | ' .
    date('n/j/Y g:i a', strtotime($story['created_on'])) . '</span>
    ' . $comment['comment'] . '</div>';
}