<?php
$content = '
' . $error . '<br />

<label>Username:</label> ' . $details['username'] . '<br />
<label>Email:</label>' . $details['email'] . ' <br />

<form method="post">
' . $error . '<br />
    <label>Password</label> <input type="password" name="password" value="" /><br />
    <label>Password Again</label> <input type="password" name="password_check" value="" /><br />
    <input type="submit" name="updatepw" value="Update password" />
</form>';